# Generated by Django 5.0.1 on 2024-04-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeslots', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='user',
            new_name='enployee',
        ),
    ]
