# Generated by Django 5.0.1 on 2024-04-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeslots', '0003_remove_timeslot_enployee_timeslot_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='employee',
            new_name='user',
        ),
    ]
