# Generated by Django 5.0.1 on 2024-04-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_duration_alter_service_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='user',
            new_name='staff',
        ),
    ]
