# Generated by Django 5.0.1 on 2024-04-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_user_service_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='staff',
            new_name='employee',
        ),
    ]
