# Generated by Django 5.0.1 on 2024-04-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
